### ISSUE TITLE
[bug] nflag 체크에서 segfalut 발생

### ISSUE THREAD

**Issue by jis-kim** [strawberryShell/minishell#18]
버그 적다가 그냥 엔터를 쳐버리고 말았군요.....
echo에 아무 인자도 들어가지 않으면  is_nflag에서 세그폴트가 발생합니다.
is_nflag 전에 null체크해주면 되는 문제므로 제가 고치겠습니다..

**Comment by jis-kim** [comment]
처리완료~~ 다음 commit에 태그하겠습니다.

**Comment by sehhong3317** [comment]
ㅠㅠ 왜 그랫즤... 체크해주셔서 감사해요!:)
